#!/usr/bin/env python3
"""Writes vst/layout.conf (Force Shadow widget syntax) for Lucky Dip. Same pages and positions as force-kit-builder's
addon/shadow_page.conf; the theme block is copied from it verbatim. Run by vst/build.sh."""
import os
CATS = [("kick", "KICK"), ("snare", "SNARE"), ("rim", "RIM"), ("clap", "CLAP"), ("hat", "HAT"), ("closed_hat", "CLOSED HAT"),
        ("open_hat", "OPEN HAT"), ("tom", "TOM"), ("conga", "CONGA"), ("percussion", "PERC"), ("crash", "CRASH"),
        ("ride", "RIDE"), ("cymbal", "CYMBAL"), ("fx", "FX"), ("glitch", "GLITCH"), ("vox", "VOX"), ("bass", "BASS"),
        ("synth", "SYNTH"), ("stab", "STAB"), ("chord", "CHORD"), ("lead", "LEAD"), ("pad", "PAD"), ("other", "OTHER")]
THEME = """style=td3
theme_bg=1a1a1a
theme_panel=1a1a1a
theme_line=2e2e2e
theme_ink=f2f2f2
theme_ink_dim=aaaaaa
theme_ink_faint=666666
theme_accent=ff8f00
theme_accent_hi=ffb74d
theme_knob_face=2a2a2a
theme_knob_ring=000000
theme_bar=2a2a2a
theme_seg_active=ff8f00
theme_seg_inactive=2a2a2a
theme_seg_active_tx=000000
theme_btn_text=ffffff
theme_well=000000
theme_knob_off=444444
theme_tab_on=2a2a2a
theme_lcd=000000
theme_box=202020
theme_btn_bg=3a3a3c
theme_chrome_ink=ffffff
theme_go_on=00e676
theme_go_off=616161
theme_tabs=1a1a1a
"""
o = ["# Lucky Dip skin layout (generated by vst/gen_layout.py; edit that, not this).",
     "# Pages and positions follow force-kit-builder's shadow page; the theme block is that page's, verbatim.", THEME,
     "[tab PADS]", 'readout cx=640 cy=36 w=780 h=48 label="" key=status get=status']
q = []
for i in range(16):
    x = 20 + (i % 4) * 315
    y = 82 + (i // 4) * 162
    n = i + 1
    o += ['frame   x=%d y=%d w=295 h=150 title="PAD %d"' % (x, y, n),
          'readout cx=%d cy=%d w=270 h=30 label="" key=pad%d_name get=pad%d_name' % (x + 147, y + 36, n, n),
          'button  cx=%d cy=%d label="PLAY" key=pad%d_play color=e53935' % (x + 78, y + 122, n),
          'button  cx=%d cy=%d label="REROLL" key=pad%d_reroll' % (x + 215, y + 122, n),
          'readout cx=%d cy=%d w=130 h=26 label="" key=pad%d_pill get=pad%d_pill' % (x + 85, y + 70, n, n),
          'toggle  cx=%d cy=%d label="LOCK" key=pad%d_lock' % (x + 225, y + 66, n)]
    q.append("pad%d_gain" % n)
# the pad gains are not on the tiles (no room): Q-Links 1-16 map to them via the PADS set below
o += ['qlinks "PADS" = ' + ",".join(q)]
o += ["", "[tab DETAIL]"]
for k, (key, lab) in enumerate(CATS):
    o.append('toggle  cx=%d cy=%d label="%s" key=sel_cat_%s' % (105 + (k % 6) * 138, 162 + (k // 6) * 81, lab, key))
o += ['frame   x=20 y=82 w=860 h=380 title="CATEGORY - TAP TO TOGGLE"',
      'frame   x=900 y=82 w=340 h=380 title="KIT"',
      'button  cx=1070 cy=163 label="GENERATE ALL" key=generate color=f2f2f2 text_color=555555',
      'button  cx=1070 cy=225 label="CLEAR ALL" key=clear_all',
      'button  cx=1070 cy=287 label="NORMALISE" key=normalise',
      'button  cx=1070 cy=349 label="RESCAN LIBRARY" key=rescan',
      'button  cx=1070 cy=411 label="EXPORT KIT" key=export color=e53935',
      'frame   x=20 y=482 w=1240 h=246 title="PAD DETAIL"',
      'stepper cx=150 cy=554 w=220 h=44 label="" key=sel_pad prev=sel_prev next=sel_next get=sel_name',
      'knob    cx=150 cy=639 r=35 label="GAIN" key=sel_gain',
      'readout cx=660 cy=554 w=700 h=44 label="" key=sel_name get=sel_name',
      'button  cx=1140 cy=554 label="   PLAY   " key=sel_play color=e53935',
      'toggle  cx=370 cy=639 label="LOCK" key=sel_lock',
      'button  cx=520 cy=639 label="CLEAR" key=sel_clear',
      'button  cx=670 cy=639 label="REROLL" key=sel_reroll',
      'button  cx=820 cy=639 label="FAV" key=sel_fav',
      'button  cx=960 cy=639 label="REJECT" key=sel_reject']
o += ['qlinks "DETAIL" = sel_gain,sel_pad,sel_lock,sel_reroll,sel_clear,sel_play,sel_fav,sel_reject,generate,clear_all,normalise,export,rescan']
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "layout.conf"), "w").write("\n".join(o) + "\n")
