#!/usr/bin/env python3
"""Regenerate src/xpm_template.h from force-kit-builder's exporters/xpm_template.mjs
(the program template lifted from a real MPC-V 2.1 drum program; see that file's header).
    tools/gen_xpm_template.py /path/to/force-kit-builder/exporters/xpm_template.mjs > src/xpm_template.h
"""
import json, re, sys
src = open(sys.argv[1]).read()
def lit(name):
    m = re.search(r'export const %s = ("(?:[^"\\]|\\.)*");' % name, src)
    if not m: sys.exit("missing " + name)
    return json.loads(m.group(1))
def cstr(s):
    out = []
    for line in s.split("\n"):
        out.append('"' + line.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r") + '\\n"')
    return "\n    ".join(out)
print("/* generated by tools/gen_xpm_template.py from force-kit-builder: do not edit */")
print("#pragma once")
for n in ("XPM_HEAD", "XPM_PROGPADS", "XPM_PROG_PARAMS", "XPM_INSTRUMENT", "XPM_TAIL"):
    s = lit(n)
    assert s.endswith("\n")
    print("static const char *const %s =\n    %s;" % (n, cstr(s[:-1])))
